Models/QuanLySinhVien/ChuongTrinhHoc.cs
using System;
using System.Collections.Generic;

namespace qlsv.Models
{
    public class ChuongTrinhHoc
    {
        // Variables
        public string IdChuongTrinhHoc { get; set; } = null!;
        public string? TenChuongTrinhHoc { get; set; }

        // Variables linked to another table
        public virtual ICollection<ChuongTrinhHocMonHoc> ChuongTrinhHocMonHocs { get; set; }
        public virtual ICollection<SinhVien> SinhViens { get; set; }

        // Constructor
        public ChuongTrinhHoc()
        {
            ChuongTrinhHocMonHocs = new HashSet<ChuongTrinhHocMonHoc>();
            SinhViens = new HashSet<SinhVien>();
        }

        
    }
}

Models/QuanLySinhVien/ChuongTrinhHocMonHoc.cs
using System;
using System.Collections.Generic;

namespace qlsv.Models
{
    public class ChuongTrinhHocMonHoc
    {
        // Variables
        public string IdCthmonHoc { get; set; } = null!;
        public string? IdChuongTrinhHoc { get; set; }
        public string? IdMonHoc { get; set; }
        
        // Variables linked to another table
        public virtual ChuongTrinhHoc? ChuongTrinhHocs { get; set; }
        public virtual MonHoc? MonHocs { get; set; }
    }
}

Models/QuanLySinhVien/DangKyDoiLich.cs
using System;
using System.Collections.Generic;

namespace qlsv.Models
{
    public class DangKyDoiLich
    {
        // Variables
        public string? IdDangKyDoiLich { get; set; } = null!;
        public string IdThoiGian { get; set; } = null!;
        public DateTime ThoiGianBatDauHienTai { get; set; }
        public DateTime ThoiGianKetThucHienTai { get; set; }
        public DateTime ThoiGianBatDauMoi { get; set; }
        public DateTime ThoiGianKetThucMoi { get; set; }
        public int TrangThai { get; set; }
        
        public virtual ThoiGian? ThoiGians { get; set; }
    }
}

Models/QuanLySinhVien/DangKyNguyenVong.cs
using System;
using System.Collections.Generic;

namespace qlsv.Models
{
    public class DangKyNguyenVong
    {
        // Variables
        public string IdDangKyNguyenVong { get; set; } = null!;
        public string IdSinhVien { get; set; }
        public string IdMonHoc { get; set; }
        public int TrangThai { get; set; }

        // Variables linked to another table
        public virtual SinhVien? SinhViens { get; set; }
        public virtual MonHoc? MonHocs { get; set; }
    }
}

Models/QuanLySinhVien/Diem.cs
using System;
using System.Collections.Generic;

namespace qlsv.Models
{
    public class Diem
    {
        // Variables
        public string IdDiem { get; set; } = null!;
        public string? IdLopHocPhan { get; set; }
        public string? IdSinhVien { get; set; }
        public decimal? DiemQuaTrinh { get; set; }
        public decimal? DiemKetThuc { get; set; }
        public decimal? DiemTongKet { get; set; }
        public int? LanHoc { get; set; }

        // Variables linked to another table
        public virtual LopHocPhan? LopHocPhans { get; set; }
        public virtual SinhVien? SinhViens { get; set; }
    }
}

Areas/Admin/Controllers/QuanLySinhVienController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;


using qlsv.Dto;
using qlsv.Models;
using qlsv.Data;
using qlsv.Services;

namespace qlsv.Admin.Controllers;

[Area("Admin")]
public class QuanLySinhVienController : Controller
{
    // Variable
    private readonly ILogger<QuanLySinhVienController> _logger;
    private readonly QuanLySinhVienDbContext _context;

    private readonly IdentityDbContext _identityContext;

    // Constructor
    public QuanLySinhVienController(
        ILogger<QuanLySinhVienController> logger,
        QuanLySinhVienDbContext context,
        IdentityDbContext identityContext
        )
    {
        _logger = logger;
        _context = context;
        _identityContext = identityContext;
    }

    /**
     * GET: /Admin/QuanLySinhVien
     * Home Page
     */
    public IActionResult Index()
    {
        return View();
    }

    /**
     * GET: /Admin/QuanLySinhVien/Details?IdSinhVien={IdSinhVien}
     * get details sinh vien
     */
    public IActionResult Details(string IdSinhVien)
    {
        SinhVien? sv = _context.SinhViens
            .Include(x => x.ChuongTrinhHocs)
            .Include(x => x.Khoas)
            .FirstOrDefault(x => x.IdSinhVien == IdSinhVien);
        if (sv == null)
        {
            return NotFound();
        }

        return View(sv);
    }

    /**
     * GET: /Admin/QuanLySinhVie/Edit?IdSinhVien={IdSinhVien}
     * Edit sinh vien information
     */
    public IActionResult Edit(string IdSinhVien)
    {
        SinhVien? sv = _context.SinhViens
            .Include(x => x.ChuongTrinhHocs)
            .Include(x => x.Khoas)
            .FirstOrDefault(x => x.IdSinhVien == IdSinhVien);
        if (sv == null)
        {
            return NotFound();
        }

        return View(sv);
    }

    /**
     * POST: /Admin/QuanLySinhVien/Edit
     * POST Edit sinh vien information
     */
    [HttpPost]
    public async Task<IActionResult> Edit(SinhVien sv)
    {
        var qr = _context.SinhViens
            .Include(x => x.ChuongTrinhHocs)
            .Include(x => x.Khoas)
            .FirstOrDefault(x => x.IdSinhVien == sv.IdSinhVien);
        if (qr == null)
        {
            return NotFound();
        }

        qr.HoTen = sv.HoTen;
        qr.Lop = sv.Lop;
        qr.DiaChi = sv.DiaChi;
        qr.NgaySinh = sv.NgaySinh;

        _context.SaveChanges();
        return RedirectToAction("Details", new { IdSinhVien = sv.IdSinhVien });
    }

    /**
     * POST: /Admin/QuanLyGiaoVien/UploadCSV
     * Upload CSV file create list giao vien
     */
    [HttpPost]
    public async Task<IActionResult> UploadCSV(IFormFile file)
    {
        if (file == null || file.Length == 0)
        {
            return BadRequest("File not found");
        }

        var sinhviens = new List<SinhVien>();
        var _IdentitySinhviens = new List<UserCustom>();
        using (var reader = new StreamReader(file.OpenReadStream()))
        {
            while (reader.Peek() >= 0)
            {
                var line = await reader.ReadLineAsync();
                var values = line.Split(",");
                var idCTH = _context.ChuongTrinhHocs.FirstOrDefault(x => x.TenChuongTrinhHoc == values[6].Trim());
                if (idCTH == null)
                {
                    return BadRequest("Chuong trinh hoc not found");
                }
                var sv = new SinhVienDto
                {
                    IdSinhVien = values[0].Trim(),
                    HoTen = values[1].Trim(),
                    Lop = values[2].Trim(),
                    NgaySinh = DateTime.Parse(values[3].Trim()),
                    DiaChi = values[4].Trim(),
                    IdKhoa = values[5].Trim(),
                    IdChuongTrinhHoc = idCTH.IdChuongTrinhHoc,
                    Email = values[7].Trim(),
                    SoDienThoai = values[8].Trim()
                };
                if (SinhVienExists(sv).Status)
                {
                    sinhviens.Add(new SinhVien
                    {
                        IdSinhVien = sv.IdSinhVien,
                        HoTen = sv.HoTen,
                        Lop = sv.Lop,
                        NgaySinh = sv.NgaySinh,
                        DiaChi = sv.DiaChi,
                        IdKhoa = sv.IdKhoa,
                        IdChuongTrinhHoc = sv.IdChuongTrinhHoc
                    });
                    _IdentitySinhviens.Add(new UserCustom
                    {
                        IdClaim = sv.IdSinhVien,
                        UserName = sv.IdSinhVien,
                        FullName = sv.HoTen,
                        Email = sv.Email,
                        PhoneNumber = sv.SoDienThoai,
                        PasswordHash = "i1CelkDpmAmgU08yFCskzfda4mWOI12kwgW571+2OiY=" // 123
                    });
                }
                else
                {
                    return BadRequest(SinhVienExists(sv).Message);
                }
            }
        }

        _context.SinhViens.AddRange(sinhviens);
        _context.SaveChanges();
        _identityContext.Users.AddRange(_IdentitySinhviens);
        _identityContext.SaveChanges();

        // LinQ gan role cho user trong identity

        var sinhvienRole = _identityContext.Roles.FirstOrDefault(r => r.Name == "SinhVien");

        foreach (var sv in _IdentitySinhviens)
        {
            _identityContext.UserRoles.AddRange(
                new IdentityUserRole<string> { UserId = sv.Id, RoleId = sinhvienRole.Id }
            );
        }
        _identityContext.SaveChanges();

        return RedirectToAction("Index");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

    // Helper check information of user
    private StatusUploadFileDto SinhVienExists(SinhVienDto _sinhVien)
    {
        // Check id
        var id = _sinhVien.IdSinhVien;
        var sinhVien = _identityContext.Users.FirstOrDefault(x => x.IdClaim == id);
        if (sinhVien != null)
        {
            return new StatusUploadFileDto
            {
                Status = false,
                Message = "Id already exists"
            };
        }
        // Check email
        string? email = _sinhVien.Email;
        // Check null email in identity context
        var user = _identityContext.Users.FirstOrDefault(x => x.Email == email);
        if (user != null)
        {
            return new StatusUploadFileDto
            {
                Status = false,
                Message = "Email already exists"
            };
        }
        // Check so dien thoai
        string? soDienThoai = _sinhVien.SoDienThoai;
        var giaovienSoDienThoai = _identityContext.Users.FirstOrDefault(x => x.PhoneNumber == soDienThoai);
        if (giaovienSoDienThoai != null)
        {
            return new StatusUploadFileDto
            {
                Status = false,
                Message = "So dien thoai already exists"
            };
        }

        return new StatusUploadFileDto
        {
            Status = true,
            Message = "Success"
        };
    }

    [HttpPost]
    public async Task<ActionResult> UpdatePhotoUser(string IdUser, IFormFile file)
    {
        const int maxFileSize = 1024 * 1024; // 2MB
        var user = await _identityContext.Users.FirstOrDefaultAsync(u => u.IdClaim == IdUser);
        var userSinhVien = _context.SinhViens.FirstOrDefault(u => u.IdSinhVien == IdUser);

        if (user == null)
        {
            TempData["MessageUpLoadAvatar"] = "Don't find user upgrade avatar.";
            TempData["StatusUpdateAvatar"] = false;
            return NotFound();
        }
        if (file == null || file.Length == 0)
        {
            TempData["MessageUpLoadAvatar"] = "File not found.";
            TempData["StatusUpdateAvatar"] = false;
            return RedirectToAction("Edit", new { idSinhVien = IdUser });
        }
        ImageService imageService = new ImageService();
        byte[] imageData = await imageService.ToByteAsync(file);

        List<string> dotImage = new List<string>() { "jfif", "png", "webp", "jpeg", "jpg", "heic" };

        string[] fileExtension = file.FileName.Split(".");
        string extension = fileExtension[fileExtension.Length - 1];

        if (imageData != null && dotImage.Contains(extension))
        {
            if (imageData.Length <= maxFileSize)
            {
                user.ProfilePicture = imageData;
                // Convert base 64
                user.ProfilePictureBase64 = Convert.ToBase64String(imageData);
                _identityContext.SaveChanges();
                TempData["MessageUpLoadAvatar"] = "File Upload Successful.";
                TempData["StatusUpdateAvatar"] = true;
            }
            else
            {
                TempData["MessageUpLoadAvatar"] = "Please Upload A Picture Smaller Than 2 MB.";
                TempData["StatusUpdateAvatar"] = false;
            }
        }
        else
        {
            TempData["MessageUpLoadAvatar"] = "File Upload Failed, Please Upload A Picture.";
            TempData["StatusUpdateAvatar"] = false;
        }

        return RedirectToAction("Edit", new { idSinhVien = IdUser });
    }
}

Areas/Teacher/Controllers/QuanLySinhVienController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Text.Json.Nodes;
//
using qlsv.Models;
using qlsv.ViewModels;
using qlsv.Data;
using qlsv.Helpers;


namespace qlsv.Teacher.Controllers;

[Area("Teacher")]
public class QuanLySinhVienController : Controller
{
    // Variable
    private readonly ILogger<QuanLySinhVienController> _logger;
    private readonly QuanLySinhVienDbContext _context;
    private readonly JwtHelper _jwtHelper;

    // Constructor
    public QuanLySinhVienController(
        ILogger<QuanLySinhVienController> logger,
        QuanLySinhVienDbContext context,
        JwtHelper jwtHelper)
    {
        _logger = logger;
        _context = context;
        _jwtHelper = jwtHelper;
    }

    // GET: Teacher/QuanLySinhVien/Index
    public IActionResult Index()
    {
        var accessToken = HttpContext.Request.Cookies["AccsessToken"];
        var jwtToken = _jwtHelper.DecodeToken(accessToken);
        string idUser = jwtToken.Claims.FirstOrDefault(c => c.Type == "idClaim")?.Value;

        List<SinhVien> sinhViens = (from gv in _context.GiaoViens
                                    join lhp in _context.LopHocPhans on gv.IdGiaoVien equals lhp.IdGiaoVien
                                    join sv_lhp in _context.SinhVienLopHocPhans on lhp.IdLopHocPhan equals sv_lhp.IdLopHocPhan
                                    join sv in _context.SinhViens on sv_lhp.IdSinhVien equals sv.IdSinhVien
                                    where gv.IdGiaoVien == idUser
                                    select new SinhVien{
                                        IdSinhVien = sv.IdSinhVien,
                                        HoTen = sv.HoTen,
                                        Lop = sv.Lop,
                                        NgaySinh = sv.NgaySinh,
                                        DiaChi = sv.DiaChi,
                                        ChuongTrinhHocs = sv.ChuongTrinhHocs, 
                                        Khoas = sv.Khoas
                                    }).ToList();

        return View(sinhViens);
    }

    // GET: Teacher/QuanLySinhVien/Details/
    public IActionResult Details(string idSv)
    {
        var accessToken = HttpContext.Request.Cookies["AccsessToken"];
        var jwtToken = _jwtHelper.DecodeToken(accessToken);
        string idGv = jwtToken.Claims.FirstOrDefault(c => c.Type == "idClaim")?.Value;
        if (string.IsNullOrEmpty(idGv))
        {
            return Unauthorized();
        }

        var diems = (
            from d in _context.Diems
            join sv in _context.SinhViens on d.IdSinhVien equals sv.IdSinhVien
            join lhp in _context.LopHocPhans on d.IdLopHocPhan equals lhp.IdLopHocPhan
            where d.IdSinhVien == idSv && lhp.IdGiaoVien == idGv
            select new Diem
            {
                IdDiem = d.IdDiem,
                IdSinhVien = d.IdSinhVien,
                IdLopHocPhan = d.IdLopHocPhan,
                SinhViens = sv,
                DiemQuaTrinh = d.DiemQuaTrinh,
                DiemKetThuc = d.DiemKetThuc,
                DiemTongKet = d.DiemTongKet
            }
        ).ToList();
        ViewBag.TenSinhVien = _context.SinhViens.Find(idSv)?.HoTen;

        return View(diems);
    }

    // POST: Teacher/QuanLySinhVien/NhapDiem/
    [HttpPost]
    public IActionResult NhapDiem(List<NhapDiem> diems)
    {
        foreach (var diem in diems)
        {
            if (!_context.Diems.Any(d => d.IdDiem == diem.IdDiem))
            {
                return BadRequest(new JsonObject { { "message", "Dữ liệu không hợp lệ" } });
            }

            var diemToUpdate = _context.Diems.Find(diem.IdDiem);
            if (diemToUpdate == null) continue;

            decimal? diemQuaTrinh = ParseScore(diem.DiemQuaTrinh, "Điểm quá trình");
            decimal? diemKetThuc = ParseScore(diem.DiemKetThuc, "Điểm kết thúc");
            decimal? diemTongKet = ParseScore(diem.DiemTongKet, "Điểm tổng kết");

            if (diemQuaTrinh == null || diemKetThuc == null || diemTongKet == null)
            {
                return BadRequest(new JsonObject { { "message", "Điểm nhập vào không hợp lệ" } });
            }

            diemToUpdate.DiemQuaTrinh = diemQuaTrinh.Value;
            diemToUpdate.DiemKetThuc = diemKetThuc.Value;
            diemToUpdate.DiemTongKet = diemTongKet.Value;

            _context.Diems.Update(diemToUpdate);
        }

        _context.SaveChanges();
        return Ok(new JsonObject { { "message", "Cập nhật điểm thành công" } });
    }

    private decimal? ParseScore(string scoreString, string scoreName)
    {
        if (!decimal.TryParse(scoreString, out var score) || score < 0 || score > 10)
        {
            _logger.LogWarning("{ScoreName} không hợp lệ: {ScoreString}", scoreName, scoreString);
            return null;
        }
        return score;
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Areas/Admin/Views/QuanLySinhVien/Edit.cshtml
@model SinhVien

@{
    ViewBag.Title = "Chỉnh Sửa Thông Tin Sinh Vien";
}

@section Scripts {
    <script>
        // Xu li chon anh roi hien thi anh ra sau khi chon tu file
        function displaySelectedImage(event, elementId) {
            const selectedImage = document.getElementById(elementId);
            const fileInput = event.target;

            if (fileInput.files && fileInput.files[0]) {
                const reader = new FileReader();

                reader.onload = function (e) {
                    selectedImage.src = e.target.result;
                };

                reader.readAsDataURL(fileInput.files[0]);
            }
        }
        document.addEventListener("DOMContentLoaded", function () {
            var base64_Avatar = document.getElementById("selectedAvatar").getAttribute("src");
            if (base64_Avatar != null) {
                document.getElementById("selectedAvatar").src = base64_Avatar;
            }
        });

        // Xu li thay doi mat khau
        function changePassword() {
            var newPassword = document.getElementById("newPassword").value;
            var confirmPassword = document.getElementById("confirmPassword").value;
            var IdSinhVien = document.getElementById("IdSinhVien").value;

            if (newPassword != confirmPassword) {
                alert("Mật khẩu mới không trùng khớp");
                return;
            }

            $.ajax({
                url: '/api/SinhVien/adminupdatepassword',
                type: "POST",
                contentType: "application/json",
                data: JSON.stringify({
                    idUser: IdSinhVien,
                    newPassword: newPassword,
                    confirmPassword: confirmPassword
                }),
                success: function (response) {
                    alert("Thay đổi mật khẩu thành công");
                },
                error: function (response) {
                    console.log(response.status, response.text);
                    alert("Thay đổi mật khẩu thất bại");
                }
            });
        }
    </script>
    <script>
        $(document).ready(function () {
            // Xu li lay anh tu sever va hien thi ra view
            $.ajax({
                url: '/api/avatar/user/@Model.IdSinhVien',
                type: "GET",
                success: function (data) {
                    if (data.profilePictureBase64 != null) {
                        const src = 'data:image/png;base64,' + data.profilePictureBase64;
                        $('#selectedAvatar').attr('src', src);
                    } else {
                        $('#selectedAvatar').attr('src', '/sb-admin/img/undraw_profile.svg');
                    }
                }
            });

            // AJAX edit data sinh vien
            $('#changePasswordForm').submit(function (e) {
                e.preventDefault();
            });

        });
    </script>
}

<div class="container-xl px-4 mt-4">
    <!-- Account page navigation-->
    <hr class="mt-0 mb-4">
    <div class="row">
        <div class="col-xl-4">
            <!-- Profile picture card-->
            <div class="card mb-4 mb-xl-0">
                <div>
                    <form asp-action="UpdatePhotoUser" asp-area="Admin" asp-controller="QuanLysinhvien"
                        asp-route-IdUser="@Model.IdSinhVien" method="post" enctype="multipart/form-data">
                        <div class="d-flex justify-content-center mb-4">
                            <img class="img-fluid rounded-circle" id="selectedAvatar" src="" alt="..."
                                style="width: 200px; height: 200px;">
                        </div>
                        <div class="d-flex justify-content-center mb-4">
                            <div data-mdb-ripple-init class="btn btn-primary btn-rounded">
                                <label class="form-label text-white m-1" for="file">Choose file</label>
                                <input type="file" name="file" class="form-control d-none" id="file"
                                    onchange="displaySelectedImage(event, 'selectedAvatar')" />
                            </div>
                            <div class="m-2 d-flex justify-content-center">
                                <button class="btn btn-warning" type="submit">Upload new image</button>
                            </div>
                        </div>
                        @if (ViewBag.MessageUpLoadAvatar != null)
                        {
                            string message = "";
                            string css = "";
                            if (ViewBag.StatusUpdateAvatar)
                            {
                                message = @ViewBag.MessageUpLoadAvatar;
                                css = "alert alert-success";
                            }
                            else
                            {
                                message = @ViewBag.MessageUpLoadAvatar;
                                css = "alert alert-danger";
                            }
                            <div class="@css" role="alert">
                                @message
                            </div>
                        }
                    </form>
                </div>
            </div>
        </div>
        <div class="col-xl-8">
            <!-- Account details card-->
            <div class="card mb-4">
                <div class="card-header">Account Details</div>
                <div class="card-body">
                    <form asp-action="Edit" asp-area="Admin" asp-controller="QuanLySinhVien" method="post">
                        <!-- Ho ten -->
                        <div class="mb-3">
                            <label class="small mb-1" asp-for="HoTen">Họ Và Tên</label>
                            <input asp-for="HoTen" class="form-control" placeholder="Tên Sinh Viên"
                                value="@Model.HoTen">
                            <span asp-validation-for="HoTen" class="text-danger"></span>
                        </div>
                        <!-- Lop -->
                        <div class="mb-3">
                            <label class="small mb-1" asp-for="Lop">Lớp</label>
                            <input asp-for="Lop" class="form-control" placeholder="Lớp" value="@Model.Lop">
                            <span asp-validation-for="Lop" class="text-danger"></span>
                        </div>
                        <!-- Dia Chi -->
                        <div class="mb-3">
                            <label class="small mb-1" asp-for="DiaChi">Địa Chỉ</label>
                            <input asp-for="DiaChi" class="form-control" placeholder="Địa Chỉ"
                                value="@Model.DiaChi">
                            <span asp-validation-for="DiaChi" class="text-danger"></span>
                        </div>
                        <!-- Ngày Sinh -->
                        <div class="mb-3">
                            <label class="small mb-1" asp-for="NgaySinh">Ngày Sinh</label>
                            <input asp-for="NgaySinh" type="date" class="form-control" placeholder="Ngày Sinh"
                                value="@(Model.NgaySinh.HasValue ? Model.NgaySinh.Value.ToString("yyyy-MM-dd") : "")">
                            <span asp-validation-for="NgaySinh" class="text-danger"></span>
                        </div>
                        
                        <!-- Save changes button-->
                        <input hidden class="hidden" asp-for="IdChuongTrinhHoc" value="@Model.IdChuongTrinhHoc">
                        <input hidden class="hidden" asp-for="IdKhoa" value="@Model.IdKhoa">
                        <input hidden class="hidden" asp-for="IdSinhVien" value="@Model.IdSinhVien">
                        <button class="btn btn-primary" type="submit">Save changes</button>
                    </form>
                </div>
            </div>
            <!-- Thay doi mat khau bang ajax -->
            <div class="card mb-4">
                <div class="card-header">Thay Đổi Mật Khẩu</div>
                <div class="card-body">
                    <form id="changePasswordForm">
                        <div class="mb-3">
                            <label class="small mb-1" for="newPassword">Mật Khẩu Mới</label>
                            <input class="form-control" id="newPassword" type="password"
                                placeholder="Enter your new password">
                        </div>
                        <div class="mb-3">
                            <label class="small mb-1" for="confirmPassword">Nhập Lại Mật Khẩu Mới</label>
                            <input class="form-control" id="confirmPassword" type="password"
                                placeholder="Confirm your new password">
                        </div>
                        <input hidden class="hidden" id="IdSinhVien" value="@Model.IdSinhVien">
                        <button class="btn btn-primary" type="button" onclick="changePassword()">Change
                            Password</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Areas/Admin/Views/QuanLySinhVien/Index.cshtml
@section Styles {
    <link href="~/sb-admin/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
}

@section Scripts {
    <!-- Page level plugins -->
    <script src="~/sb-admin/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/sb-admin/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script>
        $(document).ready(function () {
            $('#dataTable').DataTable({
                ajax: {
                    url: '/api/sinhvien/',
                    type: 'GET',
                    dataSrc: '',
                },
                language: {
                    url: '/sb-admin/json/data_tables_vi.json',
                },
                columns: [
                    {
                        data: 'tenSinhVien',
                        render: function (data, type, row) {
                            return '<a href="/Admin/QuanLySinhVien/Details?IdSinhVien=' + row.idSinhVien + '">' + data + '</a>';
                        }
                    },
                    {
                        data: 'lop',
                    },
                    {
                        data: 'ngaySinh',
                    },
                    {
                        data: 'diaChi',
                    },
                    {
                        data: 'tenChuongTrinhHoc',
                        render: function (data, type, row) {
                            return '<a href="/Admin/QuanLyChuongTrinhHoc/Details?IdChuongTrinhHoc=' + row.idChuongTrinhHoc + '">' + data + '</a>';
                        }
                    },
                    {
                        data: 'tenKhoa',
                        render: function (data, type, row) {
                            return '<a href="/Admin/QuanLyKhoa/Details?IdKhoa=' + row.idKhoa + '">' + data + '</a>';
                        }
                    },
                ],
            });
        });
    </script>
}

<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Bảng dữ liệu Sinh Viên</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Họ Và Tên</th>
                            <th>Lớp</th>
                            <th>Ngày Sinh</th>
                            <th>Địa Chỉ</th>
                            <th>Chương Trình Học</th>
                            <th>Khoa</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Họ Và Tên</th>
                            <th>Lớp</th>
                            <th>Ngày Sinh</th>
                            <th>Địa Chỉ</th>
                            <th>Chương Trình Học</th>
                            <th>Khoa</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>

</div>

<!-- Button load csv file -->
<div class="container-fluid mb-4">
    <form asp-action="UploadCSV" asp-controller="QuanLySinhVien" asp-area="Admin"
        method="post" enctype="multipart/form-data">
        <input type="file" name="file" accept=".csv" />
        <button type="submit" class="btn btn-primary" id="loadcsv">
            Upload CSV
        </button>
    </form>
</div>
<!-- /.container-fluid -->