Areas/Admin/Controllers/QuanLyGiaoVienController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using qlsv.Data;
using Microsoft.EntityFrameworkCore;

//
using qlsv.Models;
using qlsv.Services;
using qlsv.Dto;
using Microsoft.AspNetCore.Identity;

namespace qlsv.Admin.Controllers;

[Area("Admin")]
public class QuanLyGiaoVienController : Controller
{
    // Variable
    private readonly ILogger<QuanLyGiaoVienController> _logger;
    private readonly QuanLySinhVienDbContext _context;
    private readonly IdentityDbContext _identityContext;

    // Constructor
    public QuanLyGiaoVienController(
        ILogger<QuanLyGiaoVienController> logger,
        QuanLySinhVienDbContext context,
        IdentityDbContext identityContext)
    {
        _logger = logger;
        _context = context;
        _identityContext = identityContext;
    }

    /**
     * GET: /Admin/QuanLyGiaoVien
     * Home Page
     */
    public IActionResult Index()
    {
        return View();
    }

    // GET: /Admin/QuanLyGiaoVien/{id}
    public IActionResult Details(string IdGiaoVien)
    {
        var gv = _context.GiaoViens
                        .Include(x => x.Khoas)
                        .FirstOrDefault(g => g.IdGiaoVien == IdGiaoVien);

        return View(gv);
    }

    // GET: /Admin/QuanLyGiaoVien/Edit/{id}
    public IActionResult Edit(string IdGiaoVien)
    {
        var giaovien = (
            from gv in _context.GiaoViens
            where gv.IdGiaoVien == IdGiaoVien
            join khoa in _context.Khoas on gv.IdKhoa equals khoa.IdKhoa
            select new GiaoVien
            {
                IdGiaoVien = gv.IdGiaoVien,
                TenGiaoVien = gv.TenGiaoVien,
                SoDienThoai = gv.SoDienThoai,
                Email = gv.Email,
                IdKhoa = gv.IdKhoa,
                Khoas = khoa
            }
        ).FirstOrDefault();

        // Pass TempData values to ViewBag for display
        ViewBag.MessageUpLoadAvatar = TempData["MessageUpLoadAvatar"];
        ViewBag.StatusUpdateAvatar = TempData["StatusUpdateAvatar"];

        return View(giaovien);
    }

    // POST: /Admin/QuanLyGiaoVien/Edit/{id}
    [HttpPost]
    public IActionResult Edit(GiaoVien gv)
    {
        if (ModelState.IsValid)
        {
            _context.Update(gv);
            _context.SaveChanges();
            return RedirectToAction("Details", new { IdGiaoVien = gv.IdGiaoVien });
        }
        return View(gv);
    }

    // POST: /Admin/QuanLyGiaoVien/UpgraeAvatar/{id}
    [HttpPost]
    public async Task<IActionResult> UpgraeAvatar(string IdGiaoVien, IFormFile file)
    {
        const int maxFileSize = 1024 * 1024; // 2MB
        var user = await _identityContext.Users.FirstOrDefaultAsync(x => x.IdClaim == IdGiaoVien);
        if (user == null)
        {
            return NotFound("user not found");
        }
        if (file == null || file.Length == 0)
        {
            return RedirectToAction("Edit", new { id = IdGiaoVien });

        }
        ImageService imageService = new ImageService();
        byte[] imageData = await imageService.ToByteAsync(file);

        List<string> dotImage = new List<string>() { "png", "webp", "jpeg", "jpg", "heic" };

        string[] fileExtension = file.FileName.Split(".");
        string extension = fileExtension[fileExtension.Length - 1];

        if (imageData != null && dotImage.Contains(extension))
        {
            if (imageData.Length <= maxFileSize)
            {
                user.ProfilePicture = imageData;
                _context.SaveChanges();
            }
        }
        return RedirectToAction("Edit", new { id = IdGiaoVien });
    }

    /**
     * POST: /Admin/QuanLyGiaoVien/UploadCSV
     * Upload CSV file create list giao vien
     */
    [HttpPost]
    public async Task<IActionResult> UploadCSV(IFormFile file)
    {
        if (file == null || file.Length == 0)
        {
            return BadRequest("File not found");
        }

        var giaoviens = new List<GiaoVien>();
        var IdentityGiaoViens = new List<UserCustom>();
        using (var reader = new StreamReader(file.OpenReadStream()))
        {
            while (reader.Peek() >= 0)
            {
                var line = await reader.ReadLineAsync();
                var values = line.Split(",");
                var gv = new GiaoVienDto
                {
                    IdGiaoVien = values[0].Trim(),
                    TenGiaoVien = values[1].Trim(),
                    SoDienThoai = values[2].Trim(),
                    Email = values[3].Trim(),
                    IdKhoa = values[4].Trim()
                };
                if (GiaoVienExists(gv).Status)
                {
                    giaoviens.Add(new GiaoVien
                    {
                        IdGiaoVien = gv.IdGiaoVien,
                        TenGiaoVien = gv.TenGiaoVien,
                        SoDienThoai = gv.SoDienThoai,
                        Email = gv.Email,
                        IdKhoa = gv.IdKhoa
                    });
                    IdentityGiaoViens.Add(new UserCustom
                    {
                        IdClaim = gv.IdGiaoVien,
                        UserName = gv.IdGiaoVien,
                        Email = gv.Email,
                        PhoneNumber = gv.SoDienThoai,
                        FirstName = gv.TenGiaoVien,
                        PasswordHash = "i1CelkDpmAmgU08yFCskzfda4mWOI12kwgW571+2OiY=" // 123
                    });
                }
                else
                {
                    return BadRequest(GiaoVienExists(gv).Message);
                }
            }
        }

        _context.GiaoViens.AddRange(giaoviens);
        _context.SaveChanges();
        _identityContext.Users.AddRange(IdentityGiaoViens);
        _identityContext.SaveChanges();

        var giaovienRole = _identityContext.Roles.FirstOrDefault(r => r.Name == "GiaoVien");

        foreach (var gv in IdentityGiaoViens)
        {
            _identityContext.UserRoles.AddRange(
                new IdentityUserRole<string> { UserId = gv.Id, RoleId = giaovienRole.Id }
            );
        }
        _identityContext.SaveChanges();

        return RedirectToAction("Index");
    }


    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

    // Helper check information of user
    private StatusUploadFileDto GiaoVienExists(GiaoVienDto giaoVienDto)
    {
        // Check id
        var id = giaoVienDto.IdGiaoVien;
        var giaovien = _identityContext.Users.FirstOrDefault(x => x.IdClaim == id);
        if (giaovien != null)
        {
            return new StatusUploadFileDto
            {
                Status = false,
                Message = "Id already exists"
            };
        }
        // Check email
        string? email = giaoVienDto.Email;
        // Check null email in identity context
        var user = _identityContext.Users.FirstOrDefault(x => x.Email == email);
        if (user != null)
        {
            return new StatusUploadFileDto
            {
                Status = false,
                Message = "Email already exists"
            };
        }
        // Check so dien thoai
        string? soDienThoai = giaoVienDto.SoDienThoai;
        var giaovienSoDienThoai = _identityContext.Users.FirstOrDefault(x => x.PhoneNumber == soDienThoai);
        if (giaovienSoDienThoai != null)
        {
            return new StatusUploadFileDto
            {
                Status = false,
                Message = "So dien thoai already exists"
            };
        }

        return new StatusUploadFileDto
        {
            Status = true,
            Message = "Success"
        };
    }


    [HttpPost]
    public async Task<ActionResult> UpdatePhotoUser(string IdUser, IFormFile file)
    {
        const int maxFileSize = 1024 * 1024; // 2MB
        var user = await _identityContext.Users.FirstOrDefaultAsync(u => u.IdClaim == IdUser);
        var userGiaoVien = _context.GiaoViens.FirstOrDefault(u => u.IdGiaoVien == IdUser);

        if (user == null)
        {
            TempData["MessageUpLoadAvatar"] = "Don't find user upgrade avatar.";
            TempData["StatusUpdateAvatar"] = false;
            return NotFound();
        }
        if (file == null || file.Length == 0)
        {
            TempData["MessageUpLoadAvatar"] = "File not found.";
            TempData["StatusUpdateAvatar"] = false;
            return RedirectToAction("Edit", new { idGiaoVien = IdUser });
        }
        ImageService imageService = new ImageService();
        byte[] imageData = await imageService.ToByteAsync(file);

        List<string> dotImage = new List<string>() { "jfif", "png", "webp", "jpeg", "jpg", "heic" };

        string[] fileExtension = file.FileName.Split(".");
        string extension = fileExtension[fileExtension.Length - 1];

        if (imageData != null && dotImage.Contains(extension))
        {
            if (imageData.Length <= maxFileSize)
            {
                user.ProfilePicture = imageData;
                // Convert base 64
                user.ProfilePictureBase64 = Convert.ToBase64String(imageData);
                _identityContext.SaveChanges();
                TempData["MessageUpLoadAvatar"] = "File Upload Successful.";
                TempData["StatusUpdateAvatar"] = true;
            }
            else
            {
                TempData["MessageUpLoadAvatar"] = "Please Upload A Picture Smaller Than 2 MB.";
                TempData["StatusUpdateAvatar"] = false;
            }
        }
        else
        {
            TempData["MessageUpLoadAvatar"] = "File Upload Failed, Please Upload A Picture.";
            TempData["StatusUpdateAvatar"] = false;
        }

        return RedirectToAction("Edit", new { idGiaoVien = IdUser });
    }
}

Areas/Admin/Views/QuanLyGiaoVien/Details.cshtml
@model GiaoVien

@{
    ViewBag.Title = "Chi tiết giáo viên";
}

<div class="container">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-lg-5 col-md-5 col-sm-6">
                    <div class="white-box text-center">
                        <img id="avt_user" class="img-responsive img-fluid rounded-circle" src="data:image/png;base64,AA==" width="280"
                            height="280" alt="Không Tìm Thấy Ảnh">
                    </div>
                </div>
                <div class="col-lg-7 col-md-7 col-sm-6">
                    <h2 class="box-title mt-5">Thông Tin</h2>
                    <hr class="sidebar-divider">
                    <ul class="list-unstyled">
                        <li>
                            <h5>Họ Tên: @Model.TenGiaoVien</h5>
                        </li>
                        <li>
                            <h5>Khoa: @Model.Khoas.TenKhoa</h5>
                        </li>
                        <li>
                            <h5>Email: @Model.Email</h5>
                        </li>
                        <li>
                            <h5>Số Điện Thoại: @Model.SoDienThoai</h5>
                        </li>
                    </ul>
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <a class="btn btn-primary" asp-action="Edit" asp-route-idGiaoVien="@Model.IdGiaoVien"
                                asp-area="Admin" asp-controller="QuanLyGiaoVien">Sửa</a>
                        </div>
                    </div>
                </div>

                <hr class="sidebar-divider">

                <div class="col-lg-12 col-md-12 col-sm-12">
                    <h3 class="box-title mt-5">Danh Sách Các Lớp Học Phần Dạy</h3>
                    <div class="table-responsive">
                        <div class="container-fluid">
                            <!-- DataTales LopHocPhan -->
                            <div class="card shadow mb-4">
                                <div class="card-body">
                                    <div class="table-responsive">
                                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                            <thead>
                                                <tr>
                                                    <th>Lớp Học Phần</th>
                                                    <th>Giảng Viên</th>
                                                    <th>Môn học</th>
                                                </tr>
                                            </thead>
                                            <tfoot>
                                                <tr>
                                                    <th>Lớp Học Phần</th>
                                                    <th>Giảng Viên</th>
                                                    <th>Môn học</th>
                                                </tr>
                                            </tfoot>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <hr class="sidebar-divider">

                <div class="col-lg-12 col-md-12 col-sm-12">
                    <h3 class="box-title mt-5">Lịch Dạy</h3>
                    <div class="table-responsive" id="calendar">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Styles {
    <!-- Data table -->
    <link href="~/sb-admin/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
    <!-- Calendar -->
    <link rel='stylesheet' href='~/lib/fullcalendar-6.1.15/css/v_calendar.css' />
}

@section Scripts {
    <!-- Calendar -->
    <script src='~/lib/fullcalendar-6.1.15/dist/index.global.min.js'></script>

    <!-- Data table -->
    <script src="~/sb-admin/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/sb-admin/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <script>
        $(document).ready(function () {
            // DataTables events
            $('#dataTable').DataTable(
                {
                    ajax: {
                        url: '/api/lophocphan/giaovien/@Model.IdGiaoVien',
                        type: 'GET',
                        dataSrc: '',
                    },
                    columns: [
                        {
                            data: 'tenLopHocPhan',
                            render: function (data, type, row) {
                                return '<a href="/Admin/QuanLyLopHocPhan/Details?IdLopHocPhan=' + row.idLopHocPhan + '">' + data + '</a>';
                            }
                        },
                        {
                            data: 'tenGiaoVien',
                            render: function (data, type, row) {
                                return '<a href="/Admin/QuanLyGiaoVien/Details?IdGiaoVien=' + row.idGiaoVien + '">' + data + '</a>';
                            }
                        },
                        {
                            data: 'tenMonHoc',
                            render: function (data, type, row) {
                                return '<a href="/Admin/QuanLyMonHoc/Details?IdMonHoc=' + row.idMonHoc + '">' + data + '</a>';
                            }
                        },
                    ],
                    language: {
                        url: '/sb-admin/json/data_tables_vi.json',
                    },
                }
            );

            // Avatar events
            $.ajax({
                url: '/api/avatar/user/@Model.IdGiaoVien',
                async: false,
                success: function (data) {
                    if (data.profilePictureBase64 != null) {
                        const src = 'data:image/png;base64,' + data.profilePictureBase64;
                        $('#avt_user').attr('src', src);
                    } else {
                        $('#avt_user').attr('src', '/sb-admin/img/undraw_profile.svg');
                    }
                },
                error: function (xhr, status, error) {
                    return null;
                }
            });

            // Calendar events
            var calendarEl = document.getElementById('calendar');
            var calendar = new FullCalendar.Calendar(calendarEl, {
                displayEventTime: false,
                initialView: 'dayGridMonth', // 'dayGridWeek', 'timeGridDay', 'listWeek'
                headerToolbar: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'dayGridMonth,timeGridWeek,timeGridDay'
                },
                buttonText: {
                    today: 'Hôm nay',
                    month: 'Tháng',
                    week: 'Tuần',
                    day: 'Ngày',
                    list: 'Danh sách',
                },
                locale: 'vi',
                timeZone: 'Asia/Ho_Chi_Minh',
                titleFormat: {},
                events: function (fetchInfo, successCallback, failureCallback) {
                    $.ajax({
                        url: '/api/calendar/giaovien/@Model.IdGiaoVien',
                        type: 'GET',
                        dataType: 'json',
                        success: function (data) {
                            var events = data.map(function (item) {
                                return {
                                    id: item.id,
                                    groupId: item.groupId,
                                    title: item.title,
                                    description: item.description,
                                    start: item.start,
                                    end: item.end,
                                };
                            });
                            successCallback(events);
                        },
                        error: function () {
                            failureCallback();
                        }
                    });
                }
            });
            calendar.render();
            window.calendar = calendar;
        });
    </script>
}

Areas/Admin/Views/QuanLyGiaoVien/Edit.cshtml
@model GiaoVien

@{
    ViewBag.Title = "Details User";
}

@section Scripts {
    <script>
        // Xu li chon anh roi hien thi anh ra sau khi chon tu file
        function displaySelectedImage(event, elementId) {
            const selectedImage = document.getElementById(elementId);
            const fileInput = event.target;

            if (fileInput.files && fileInput.files[0]) {
                const reader = new FileReader();

                reader.onload = function (e) {
                    selectedImage.src = e.target.result;
                };

                reader.readAsDataURL(fileInput.files[0]);
            }
        }
        document.addEventListener("DOMContentLoaded", function () {
            var base64_Avatar = document.getElementById("selectedAvatar").getAttribute("src");
            if (base64_Avatar != null) {
                document.getElementById("selectedAvatar").src = base64_Avatar;
            }
        });

        // Xu li thay doi mat khau
        function changePassword() {
            var newPassword = document.getElementById("newPassword").value;
            var confirmPassword = document.getElementById("confirmPassword").value;
            var idGiaoVien = document.getElementById("idGiaoVien").value;

            if (newPassword != confirmPassword) {
                alert("Mật khẩu mới không trùng khớp");
                return;
            }

            $.ajax({
                url: '/api/GiaoVien/adminupdatepassword',
                type: "POST",
                headers: {
                    'Accept': '*/*',
                    'Content-Type': 'application/json'
                },
                data: JSON.stringify({
                    idUser: idGiaoVien,
                    newPassword: newPassword,
                    confirmPassword: confirmPassword
                }),
                success: function (response) {
                    alert("Thay đổi mật khẩu thành công");
                },
                error: function (response) {
                    alert("Thay đổi mật khẩu thất bại");
                    console.log(response.status, response.text);
                }
            });
        }
    </script>
    <script>
        $(document).ready(function () {
            // Xu li lay anh tu sever va hien thi ra view
            $.ajax({
                url: '/api/avatar/user/@Model.IdGiaoVien',
                type: "GET",
                success: function (data) {
                    if (data.profilePictureBase64 != null) {
                        const src = 'data:image/png;base64,' + data.profilePictureBase64;
                        $('#selectedAvatar').attr('src', src);
                    } else {
                        $('#selectedAvatar').attr('src', '/sb-admin/img/undraw_profile.svg');
                    }
                }
            });

            // Xu li lay danh sach khoa tu sever va hien thi ra view
            $.ajax({
                url: '/api/khoa',
                type: "GET",
                success: function (response) {
                    if (response != null) {
                        response.forEach(function (khoa) {
                            var option = document.createElement("option");
                            option.text = khoa.tenKhoa;
                            option.value = khoa.idKhoa;
                            if (khoa.idKhoa == "@Model.IdKhoa") {
                                option.selected = true;
                            }
                            document.querySelector("select[name='IdKhoa']").appendChild(option);
                        });

                    }
                }
            });

            // Get LopHocPhan cua GiaoVien de xem co duoc thay doi khoa khong
            $.ajax({
                url: '/api/LopHocPhan/giaovien/@Model.IdGiaoVien',
                type: 'GET',
                success: function (res) {
                    if (res.length) {
                        document.querySelector("select[name='IdKhoa']").disabled = true;
                        console.log("Khoa Khong The Thay Thoi Khi Dang Day Lop Hoc Phan");

                    }
                }
            });

        });
    </script>
}

<div class="container-xl px-4 mt-4">
    <!-- Account page navigation-->
    <hr class="mt-0 mb-4">
    <div class="row">
        <div class="col-xl-4">
            <!-- Profile picture card-->
            <div class="card mb-4 mb-xl-0">
                <div>
                    <form asp-action="UpdatePhotoUser" asp-area="Admin" asp-controller="QuanLyGiaoVien"
                        asp-route-IdUser="@Model.IdGiaoVien" method="post" enctype="multipart/form-data">
                        <div class="d-flex justify-content-center mb-4">
                            <img class="img-fluid rounded-circle" id="selectedAvatar" src="" alt="..."
                                style="width: 200px; height: 200px;">
                        </div>
                        <div class="d-flex justify-content-center mb-4">
                            <div data-mdb-ripple-init class="btn btn-primary btn-rounded">
                                <label class="form-label text-white m-1" for="file">Choose file</label>
                                <input type="file" name="file" class="form-control d-none" id="file"
                                    onchange="displaySelectedImage(event, 'selectedAvatar')" />
                            </div>
                            <div class="m-2 d-flex justify-content-center">
                                <button class="btn btn-warning" type="submit">Upload new image</button>
                            </div>
                        </div>
                        @if (ViewBag.MessageUpLoadAvatar != null)
                        {
                            string message = "";
                            string css = "";
                            if (ViewBag.StatusUpdateAvatar)
                            {
                                message = @ViewBag.MessageUpLoadAvatar;
                                css = "alert alert-success";
                            }
                            else
                            {
                                message = @ViewBag.MessageUpLoadAvatar;
                                css = "alert alert-danger";
                            }
                            <div class="@css" role="alert">
                                @message
                            </div>
                        }
                    </form>
                </div>
            </div>
        </div>
        <div class="col-xl-8">
            <!-- Account details card-->
            <div class="card mb-4">
                <div class="card-header">Account Details</div>
                <div class="card-body">
                    <form asp-action="Edit" asp-area="Admin" asp-controller="QuanLyGiaoVien" method="post">
                        <div class="mb-3">
                            <label class="small mb-1" asp-for="TenGiaoVien">Họ Và Tên</label>
                            <input asp-for="TenGiaoVien" class="form-control" placeholder="Tên Giáo Viên"
                                value="@Model.TenGiaoVien">
                            <span asp-validation-for="TenGiaoVien" class="text-danger"></span>
                        </div>
                        <div class="mb-3">
                            <label class="small mb-1" asp-for="Email">Email</label>
                            <input asp-for="Email" class="form-control" placeholder="Địa Chỉ Email"
                                value="@Model.Email">
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                        <div class="mb-3">
                            <label class="small mb-1" asp-for="SoDienThoai">Số Điện Thoại</label>
                            <input asp-for="SoDienThoai" class="form-control" placeholder="Số Điện Thoại Giáo Viên"
                                value="@Model.SoDienThoai">
                            <span asp-validation-for="SoDienThoai" class="text-danger"></span>
                        </div>
                        <div class="mb-3">
                            <!-- select khoa -->
                            <label class="small mb-1" asp-for="IdKhoa">Khoa</label>
                            <select asp-for="IdKhoa" class="form-control">
                                <option value="">-- Chọn Khoa --</option>
                            </select>
                            <span asp-validation-for="IdKhoa" class="text-danger"></span>
                        </div>
                        <!-- Save changes button-->
                        <input hidden class="hidden" asp-for="IdGiaoVien" value="@Model.IdGiaoVien">
                        <button class="btn btn-primary" type="submit">Save changes</button>
                    </form>
                </div>
            </div>
            <!-- Thay doi mat khau bang ajax -->
            <div class="card mb-4">
                <div class="card-header">Thay Đổi Mật Khẩu</div>
                <div class="card-body">
                    <form id="changePasswordForm">
                        @* <div class="mb-3">
                            <label class="small mb-1" for="oldPassword">Mật Khẩu Hiện Tại</label>
                            <input class="form-control" id="oldPassword" type="password"
                                placeholder="Enter your current password">
                        </div> *@
                        <div class="mb-3">
                            <label class="small mb-1" for="newPassword">Mật Khẩu Mới</label>
                            <input class="form-control" id="newPassword" type="password"
                                placeholder="Enter your new password">
                        </div>
                        <div class="mb-3">
                            <label class="small mb-1" for="confirmPassword">Nhập Lại Mật Khẩu Mới</label>
                            <input class="form-control" id="confirmPassword" type="password"
                                placeholder="Confirm your new password">
                        </div>
                        <input hidden class="hidden" id="idGiaoVien" value="@Model.IdGiaoVien">
                        <button class="btn btn-primary" type="button" onclick="changePassword()">Change
                            Password</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>